// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnhjvoteczifqlluskdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuaGp2b3RlY3ppZnFsbHVza2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjA0MTcsImV4cCI6MjA1ODczNjQxN30.gm12Dpe1z82GB_hyzHzZ9OOv7SY4J4xoe-aijLXEHP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);